library(sf)
library(here)
library(janitor)
library(tidyverse)
library(terra)
library(ggplot2)

st_layers(here("gadm41_CHN.gpkg"))
#读取data
CHN <- st_read(here("gadm41_CHN.gpkg"),
                     layer='ADM_ADM_0')
layers <- st_layers(here("gadm41_CHN.gpkg"))

world_cities <- st_read(here("World_Cities", "World_cities.shp"))

ssp1 <-terra::rast(here("wc2.1_2.5m_tmax_BCC-CSM2-MR_ssp126_2081-2100.tif"))

ssp1_mean <- mean(ssp1)

ssp5 <-terra::rast(here("wc2.1_2.5m_tmax_BCC-CSM2-MR_ssp585_2081-2100.tif"))

#filter cities
chinese_cities <- world_cities %>%
  janitor::clean_names()%>%
  dplyr::filter(cntry_name=="China")

#ssp_diff <- ssp5-ssp1
#栅格裁剪与遮罩（crop and mask rasters）
####ssp1

CHN_diff <- ssp1 %>%
  # now crop our temp data to the extent
  terra::crop(.,CHN)

exact_CHN <- CHN_diff %>%
  terra::mask(.,CHN)

###ssp5

CHN_diff5 <- ssp5 %>%
  # now crop our temp data to the extent
  terra::crop(.,CHN)

exact_CHN5 <- CHN_diff5 %>%
  terra::mask(.,CHN)

#subtract rasters
#### sub
diff_climate_model <- exact_CHN5 - exact_CHN

#rename and extract data from points
month <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

names(diff_climate_model) <- month

CHN_city_diff<- terra::extract(diff_climate_model, chinese_cities)

#“把提取结果接回去”用 join_id 对齐后 left_join（更稳）
chinese_cities_join_ID <- chinese_cities %>%
  # make a new column with first row as 1 and the number ends at the last row (e.g. last row 10 = id of 10)
  dplyr::mutate(join_id= 1:n())

#Now join
CHN_city_diff2 <- chinese_cities_join_ID%>%
  dplyr::left_join(.,
                   CHN_city_diff,
                   by = c("join_id" = "ID"))

#去几何、整形与分面直方图（drop geometry → tidy → facet）
# extract just the months (jan - december) columns
city_climate_diff <- CHN_city_diff2 %>%
  dplyr::select(c(,16:27))%>%
  sf::st_drop_geometry(.)%>%
  dplyr::as_tibble()

#pivot the months longer
tidy_city_diff <- city_climate_diff %>%
  tidyr::pivot_longer(everything(), 
                      names_to="Months", 
                      values_to="temp_diff")

# change the months to a factor column type (levels / ordered categories) this will be to facet
facet_plot <- tidy_city_diff %>%
  dplyr::mutate(Months = factor(Months, levels = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")))

# Plot faceted histogram
plot<-ggplot(facet_plot, 
             # plot the temp data
             aes(x=temp_diff, na.rm=TRUE))+
  #plot with histogram
  geom_histogram(color="black", binwidth = .1)+
  labs(title="Ggplot2 faceted difference in climate scenarios of max temp", 
       x="Temperature",
       y="Frequency")+
  # use the levels to facet
  facet_grid(Months ~ .)+
  theme(plot.title = element_text(hjust = 0.5))

plot
